version: '3.8'  # Specify Docker Compose version

services:
  api:  # Name of your service
    image: jetp104/api:1  # Your built image
    build:
      context: .  # Build from current directory
      dockerfile: Dockerfile  # Use your existing Dockerfile
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    entrypoint: ["python", "api.py"]    
